const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)'),menu=$('.menu'),nav=$('#navigation');
function closeMenu(focus=false){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');if(focus)menu.focus()}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
$$('a',nav).forEach(a=>a.addEventListener('click',()=>closeMenu()));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true')closeMenu(true)});
document.addEventListener('click',e=>{if(!e.target.closest('.header'))closeMenu()});
if('IntersectionObserver'in window&&!reduce.matches){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.06});$$('.intro-grid,.problem-row>div,.section-heading,.project,.about-grid,.contact-grid').forEach((el,i)=>{el.classList.add('reveal');el.style.setProperty('--reveal-delay',el.parentElement.classList.contains('problem-row')?(i%3*65)+'ms':'0ms');io.observe(el)});reduce.addEventListener('change',e=>{if(e.matches){$$('.reveal').forEach(el=>el.classList.add('visible'));io.disconnect()}})}
const workflows={before:{nodes:[['RECEIVE','Message arrives','A new enquiry lands in an inbox.'],['COPY','Update a spreadsheet','Someone re-enters the details.'],['CHASE','Ask who owns it','Context moves between people.'],['REMEMBER','Follow up manually','The next step depends on memory.']],label:'THE FRICTION',outcome:'Information moves. Ownership gets lost.'},after:{nodes:[['CAPTURE','Record it once','Capture the enquiry in one shared record.'],['ASSIGN','Give it an owner','Route it using agreed business rules.'],['CONNECT','Keep the context','Give the responsible person the information they need.'],['FOLLOW THROUGH','Make the next step clear','Use reminders and human review to keep work moving.']],label:'THE INTENDED CHANGE',outcome:'One record. Clear ownership. A visible next step.'}};
$$('[data-workflow]').forEach(button=>button.addEventListener('click',()=>{const state=button.dataset.workflow,flow=workflows[state];if(!flow)return;$$('[data-workflow]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));$('.workflow-lab').classList.toggle('is-after',state==='after');$('#workflow-display').innerHTML='<ol class="flow-nodes">'+flow.nodes.map((n,i)=>'<li style="--i:'+i+'"><span>0'+(i+1)+' / '+n[0]+'</span><strong>'+n[1]+'</strong><p>'+n[2]+'</p></li>').join('')+'</ol><div class="workflow-outcome"><span>'+flow.label+'</span><p>'+flow.outcome+'</p></div>'}));
const stages=[{caption:'01 / MAP THE OPERATION',nodes:['People','Tools','Handoffs'],text:'Understand where the work slows down.'},{caption:'02 / PLAN THE SYSTEM',nodes:['Rules','Ownership','Data flow'],text:'Define the connections and decisions the system needs.'},{caption:'03 / BUILD & CONNECT',nodes:['Prototype','Integrate','Review'],text:'Test assumptions and put the system into real work.'},{caption:'04 / MEASURE THE CHANGE',nodes:['Baseline','Feedback','Improve'],text:'Compare against the goal and decide what to improve.'}];
const steps=$$('.step'),navLinks=$$('a[href^="#"]',nav),sections=['approach','work','method','about','contact'].map(id=>document.getElementById(id));let lastStage=-1,ticking=false;
function updateScroll(){const height=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.transform='scaleX('+(height>0?Math.max(0,Math.min(1,scrollY/height)):0)+')';let current='';sections.forEach(s=>{if(s.getBoundingClientRect().top<=innerHeight*.38)current=s.id==='method'?'approach':s.id});navLinks.forEach(a=>{if(a.hash==='#'+current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')});let nearest=0,dist=Infinity;steps.forEach((s,i)=>{const r=s.getBoundingClientRect(),d=Math.abs(r.top+Math.min(r.height/2,100)-innerHeight*.45);if(d<dist){nearest=i;dist=d}});if(nearest!==lastStage){lastStage=nearest;steps.forEach((s,i)=>s.classList.toggle('active',i===nearest));const stage=stages[nearest];$('#method-caption').textContent=stage.caption;$('#method-diagram').innerHTML=stage.nodes.map(n=>'<span>'+n+'</span>').join('');$('#method-explainer').textContent=stage.text;$$('.method-track>span').forEach((s,i)=>s.classList.toggle('current',i===nearest))}ticking=false}
function scheduleScroll(){if(!ticking){requestAnimationFrame(updateScroll);ticking=true}}
addEventListener('scroll',scheduleScroll,{passive:true});addEventListener('resize',()=>{if(innerWidth>700)closeMenu();scheduleScroll()});addEventListener('load',scheduleScroll);updateScroll();$('#year').textContent=new Date().getFullYear();
$$('.project-detail,.capability-list details').forEach(details=>{const summary=$('summary',details);let animation=null;summary.addEventListener('click',e=>{if(reduce.matches||!details.animate)return;e.preventDefault();if(animation){animation.cancel();animation=null}const start=details.getBoundingClientRect().height,opening=!details.open;if(opening)details.open=true;const end=opening?details.getBoundingClientRect().height:summary.getBoundingClientRect().height;animation=details.animate([{height:start+'px'},{height:end+'px'}],{duration:240,easing:'cubic-bezier(.2,.7,.2,1)'});animation.onfinish=()=>{details.open=opening;animation=null;scheduleScroll()}})});
const form=$('#brief-form'),feedback=$('#form-feedback');
function enquiry(){const data=new FormData(form);return{subject:'Project enquiry — '+data.get('company'),body:'Name: '+data.get('name')+'\nEmail: '+data.get('email')+'\nCompany: '+data.get('company')+'\n\nWhat should work better?\n'+data.get('problem')}}
form.addEventListener('submit',e=>{e.preventDefault();const draft=enquiry();location.href='mailto:hello@deltalabs.com?subject='+encodeURIComponent(draft.subject)+'&body='+encodeURIComponent(draft.body);feedback.textContent='We requested your email app to open. Nothing has been sent yet. Review and send the draft, or use “Copy enquiry” if no email app opens.'});
$('#copy-enquiry').addEventListener('click',async e=>{if(!form.reportValidity())return;const button=e.currentTarget;button.disabled=true;button.textContent='Copying…';try{if(!navigator.clipboard)throw Error('Clipboard unavailable');const draft=enquiry();await navigator.clipboard.writeText(draft.subject+'\n\n'+draft.body);feedback.textContent='Enquiry copied. Paste it into an email to hello@deltalabs.com. Nothing has been sent yet.'}catch{feedback.textContent='Copy was unavailable. Your details are still in the form; select and copy them manually, or use “Open email draft”.'}finally{button.disabled=false;button.textContent='Copy enquiry'}});
